/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useAnimations, useFBX, useGLTF } from "@react-three/drei";
import type { GroupProps } from "@react-three/fiber";
import { useEffect, useMemo, useRef } from "react";
import type * as THREE from "three";

interface DeveloperProps {
  animationName?: "idle" | "salute" | "clapping" | "victory";
}

export const Developer = ({
  animationName = "idle",
  ...props
}: GroupProps & DeveloperProps) => {
  const groupRef = useRef<THREE.Group>(null);

  const gltf = useGLTF("/models/animations/developer.glb");
  const avatarScene = useMemo(() => gltf.scene.clone(true), [gltf.scene]);

  const { animations: idleAnimation } = useFBX("/models/animations/idle.fbx");
  const { animations: saluteAnimation } = useFBX(
    "/models/animations/salute.fbx"
  );
  const { animations: clappingAnimation } = useFBX(
    "/models/animations/clapping.fbx"
  );
  const { animations: victoryAnimation } = useFBX(
    "/models/animations/victory.fbx"
  );

  idleAnimation[0].name = "idle";
  saluteAnimation[0].name = "salute";
  clappingAnimation[0].name = "clapping";
  victoryAnimation[0].name = "victory";

  const { actions } = useAnimations(
    [
      idleAnimation[0],
      saluteAnimation[0],
      clappingAnimation[0],
      victoryAnimation[0],
    ],
    groupRef
  );

  useEffect(() => {
    actions[animationName]?.reset().fadeIn(0.5).play();

    return () => {
      actions[animationName]?.fadeOut(0.5);
    };
  }, [animationName, actions]);

  useEffect(() => {
    avatarScene.traverse((child) => {
      const mesh = child as THREE.Mesh;
      if (!("isMesh" in mesh) || !mesh.isMesh) return;

      const meshName = mesh.name.toLowerCase();
      if (meshName.includes("glass")) {
        mesh.visible = false;
      }

      const materials = Array.isArray(mesh.material)
        ? mesh.material
        : [mesh.material];
      materials.forEach((material) => {
        const mat = material as THREE.MeshStandardMaterial;
        const materialName = mat.name?.toLowerCase() ?? "";

        if (materialName.includes("glass")) {
          mat.transparent = true;
          mat.opacity = 0;
        }

        if (
          meshName.includes("head") ||
          meshName.includes("skin") ||
          materialName.includes("skin")
        ) {
          mat.color.set("#f7d8c8");
          mat.roughness = 0.65;
          mat.metalness = 0;
        }
      });

      mesh.castShadow = true;
      mesh.receiveShadow = true;
    });
  }, [avatarScene]);

  return (
    <group {...props} ref={groupRef} dispose={null}>
      <primitive object={avatarScene} />
    </group>
  );
};

useGLTF.preload("/models/animations/developer.glb");
